const rooms = [
  {
    id: 1,
    img: '/src/assets/images/room-1.jpg',
    name: 'Luxury Suite',
    bed: '1 King Bed',
    guests: 4,
    size: 30,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, necessitatibus.',
    price: 90,
  },
  {
    id: 2,
    img: '/src/assets/images/room-2.jpg',
    name: 'Standard Deluxe',
    bed: '2 single Beds',
    guests: 6,
    size: 45,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, necessitatibus.',
    price: 75,
  },
  {
    id: 3,
    img: '/src/assets/images/room-3.jpg',
    name: 'The Penthouse',
    bed: '2 King Beds',
    guests: 6,
    size: 65,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, necessitatibus.',
    price: 200,
  },
  {
    id: 4,
    img: '/src/assets/images/room-4.jpg',
    name: 'Grand Suite Room',
    bed: '1 King Bed',
    guests: 4,
    size: 70,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, necessitatibus.',
    price: 80,
  },
  {
    id: 5,
    img: '/src/assets/images/room-5.jpg',
    name: 'Junior Suite Room',
    bed: '1 Double Bed',
    guests: 3,
    size: 31,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, necessitatibus.',
    price: 69,
  },
];

export default rooms;